### ISSUE TITLE
semver-breaking: "Unused variable" errors with deny(unused).

### ISSUE THREAD

**Issue by Dirbaio** [knurling-rs/defmt#494]
The following used to build fine with defmt 0.2.1, and now fails with defmt 0.2.2. This is due to #477 

```rust
#![deny(unused)]
let x = 1; // error: unused variable: `x` if no "defmt-xxx" features are enabled
info!("x={}", x);
```

**Comment by jonas-schievink** [comment]
Also ran into this while working with a client today

**Comment by Urhengulas** [comment]
Options are reverting or releasing a new minor version?

**Comment by jonas-schievink** [comment]
We should change how the macro expands to silence the warning, then publish a new patch release

**Comment by Urhengulas** [comment]
My idea would be to just match the `args`. This should look sth like following but I am struggeling with the macro syntax:
```rust
cfg_if::cfg_if! {
    if #[#logging_enabled] {
        ...
    } else {
        match (#(&(#args)),*) {
            _ => {}
        }
    }
}
```
Currently I am getting a `error[E0433]: failed to resolve: use of undeclared crate or module 'cfg_if'`, although I specified it as a dependency for `defmt-macros`.

**Comment by Urhengulas** [comment]
Turns out I also need to add it to `defmt`. I guess it makes sense 🤔

**Comment by Urhengulas** [comment]
And it also turns out I don't need to add it to `defmt-macros`. That is a bit weird to me 😕

**Comment by Urhengulas** [comment]
@jonas-schievink I would release a new version. Should we yank the current one?

**Comment by jonas-schievink** [comment]
Yeah, probably
